
def test_posterior_sums_to_one():

def test_uniform_prior_with_all_heads(): ...
def test_strong_prior_resists_evidence(): ...
def test_sequential_updates_converge(): ...
def test_beta_conjugate_update(): ...
def test_credible_interval_contains_truth(): ...
def test_posterior_predictive(): ...
