def plot_prior_likelihood_posterior(prior, likelihood, posterior, hypotheses): ...
def plot_sequential_updating(observations: list): ...   # watch belief update with each flip
def plot_beta_updating(heads: int, tails: int): ...     # Beta-Binomial conjugate
def plot_credible_interval(posterior, hypotheses, credibility=0.95): ...